addSbtPlugin("com.dwijnand"      % "sbt-dynver"   % "4.1.1")
addSbtPlugin("com.dwijnand"      % "sbt-travisci" % "1.2.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.6.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray"  % "0.5.6")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.2")
